# Generated by Django 2.2 on 2019-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('idanexos', models.AutoField(db_column='idAnexos', primary_key=True, serialize=False)),
                ('anexo', models.CharField(blank=True, max_length=45, null=True)),
                ('thumb', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'anexos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idcategorias', models.AutoField(db_column='idCategorias', primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('cadastro', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CiSessions',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('timestamp', models.PositiveIntegerField()),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'ci_sessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('idcontas', models.AutoField(db_column='idContas', primary_key=True, serialize=False)),
                ('conta', models.CharField(blank=True, max_length=45, null=True)),
                ('banco', models.CharField(blank=True, max_length=45, null=True)),
                ('numero', models.CharField(blank=True, max_length=45, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cadastro', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'contas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('iddocumentos', models.AutoField(db_column='idDocumentos', primary_key=True, serialize=False)),
                ('documento', models.CharField(blank=True, max_length=70, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('cadastro', models.DateField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
                ('tamanho', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'documentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emitente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=45, null=True)),
                ('ie', models.CharField(blank=True, max_length=50, null=True)),
                ('rua', models.CharField(blank=True, max_length=70, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('uf', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('url_logo', models.CharField(blank=True, max_length=225, null=True)),
            ],
            options={
                'db_table': 'emitente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('idequipamentos', models.AutoField(db_column='idEquipamentos', primary_key=True, serialize=False)),
                ('equipamento', models.CharField(max_length=150)),
                ('num_serie', models.CharField(blank=True, max_length=80, null=True)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('cor', models.CharField(blank=True, max_length=45, null=True)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('tensao', models.CharField(blank=True, max_length=45, null=True)),
                ('potencia', models.CharField(blank=True, max_length=45, null=True)),
                ('voltagem', models.CharField(blank=True, max_length=45, null=True)),
                ('data_fabricacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentosOs',
            fields=[
                ('idequipamentos_os', models.AutoField(db_column='idEquipamentos_os', primary_key=True, serialize=False)),
                ('defeito_declarado', models.CharField(blank=True, max_length=200, null=True)),
                ('defeito_encontrado', models.CharField(blank=True, max_length=200, null=True)),
                ('solucao', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'equipamentos_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItensDeVendas',
            fields=[
                ('iditens', models.AutoField(db_column='idItens', primary_key=True, serialize=False)),
                ('subtotal', models.CharField(blank=True, db_column='subTotal', max_length=45, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'itens_de_vendas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lancamentos',
            fields=[
                ('idlancamentos', models.AutoField(db_column='idLancamentos', primary_key=True, serialize=False)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.CharField(max_length=15)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('baixado', models.IntegerField(blank=True, null=True)),
                ('cliente_fornecedor', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_pgto', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('anexo', models.CharField(blank=True, max_length=250, null=True)),
                ('vendas_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lancamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('idlogs', models.AutoField(db_column='idLogs', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=80, null=True)),
                ('tarefa', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('idmarcas', models.AutoField(db_column='idMarcas', primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('cadastro', models.DateField(blank=True, null=True)),
                ('situacao', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marcas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idprodutos', models.AutoField(db_column='idProdutos', primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
                ('unidade', models.CharField(blank=True, max_length=10, null=True)),
                ('precocompra', models.DecimalField(blank=True, db_column='precoCompra', decimal_places=2, max_digits=10, null=True)),
                ('precovenda', models.DecimalField(db_column='precoVenda', decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('estoqueminimo', models.IntegerField(blank=True, db_column='estoqueMinimo', null=True)),
                ('saida', models.IntegerField(blank=True, null=True)),
                ('entrada', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdutosOs',
            fields=[
                ('idprodutos_os', models.AutoField(db_column='idProdutos_os', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('subtotal', models.CharField(blank=True, db_column='subTotal', max_length=15, null=True)),
            ],
            options={
                'db_table': 'produtos_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('idservicos', models.AutoField(db_column='idServicos', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('descricao', models.CharField(blank=True, max_length=45, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicosOs',
            fields=[
                ('idservicos_os', models.AutoField(db_column='idServicos_os', primary_key=True, serialize=False)),
                ('subtotal', models.CharField(blank=True, db_column='subTotal', max_length=15, null=True)),
            ],
            options={
                'db_table': 'servicos_os',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('idvendas', models.AutoField(db_column='idVendas', primary_key=True, serialize=False)),
                ('datavenda', models.DateField(blank=True, db_column='dataVenda', null=True)),
                ('valortotal', models.CharField(blank=True, db_column='valorTotal', max_length=45, null=True)),
                ('desconto', models.CharField(blank=True, max_length=45, null=True)),
                ('faturado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vendas',
                'managed': False,
            },
        ),
    ]
