# Generated by Django 2.2 on 2019-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacoesOs',
            fields=[
                ('idobs', models.AutoField(db_column='idObs', primary_key=True, serialize=False)),
                ('os_id', models.IntegerField()),
                ('usuario_id', models.IntegerField()),
                ('dataobs', models.DateTimeField(db_column='dataObs')),
                ('observacao', models.TextField()),
            ],
            options={
                'db_table': 'observacoes_os',
                'managed': False,
            },
        ),
    ]
