# Generated by Django 2.2 on 2019-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.AutoField(db_column='idUsuarios', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(max_length=20)),
                ('rua', models.CharField(blank=True, max_length=70, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('bairro', models.CharField(blank=True, max_length=45, null=True)),
                ('cidade', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=80)),
                ('senha', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('situacao', models.IntegerField()),
                ('datacadastro', models.DateField(db_column='dataCadastro')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
