# Generated by Django 2.2 on 2019-08-31 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('idpermissao', models.AutoField(db_column='idPermissao', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('permissoes', models.TextField(blank=True, null=True)),
                ('situacao', models.IntegerField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permissoes',
                'managed': False,
            },
        ),
    ]
